# Generated by Django 3.0.1 on 2020-11-04 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allgroups', '0003_auto_20201028_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='allgroups',
            name='request',
            field=models.BooleanField(default=False),
        ),
    ]
