# Generated by Django 3.0.1 on 2020-11-05 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allgroups', '0004_allgroups_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='allgroups',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
