# Generated by Django 3.0.1 on 2020-11-07 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allgroups', '0005_allgroups_private'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allgroups',
            name='request',
        ),
    ]
