# Generated by Django 3.0.1 on 2020-11-10 01:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('allgroups', '0006_remove_allgroups_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='allgroups',
            name='discussion',
            field=models.CharField(default='nothing', max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='getUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='allgroups',
            name='userlist',
            field=models.ManyToManyField(related_name='userlist', to='allgroups.getUser'),
        ),
    ]
