# Generated by Django 3.0.1 on 2020-11-13 23:37

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('allgroups', '0007_auto_20201109_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allgroups',
            name='userlist',
        ),
        migrations.AddField(
            model_name='allgroups',
            name='userlist',
            field=django_mysql.models.ListCharField(models.CharField(max_length=10), default='null', max_length=66, size=6),
            preserve_default=False,
        ),
    ]
