# Generated by Django 3.0.1 on 2020-11-14 01:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('allgroups', '0008_auto_20201113_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allgroups',
            name='userlist',
        ),
        migrations.CreateModel(
            name='userList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allgroups', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userlist', to='allgroups.Allgroups')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
