# Generated by Django 3.0.1 on 2020-11-14 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allgroups', '0009_auto_20201113_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlist',
            name='comment',
            field=models.CharField(default='null', max_length=140),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userlist',
            name='allgroups',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userList', to='allgroups.Allgroups'),
        ),
    ]
