# Generated by Django 3.0.1 on 2020-11-14 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allgroups', '0010_auto_20201113_1908'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlist',
            old_name='comment',
            new_name='comment2',
        ),
    ]
