# Generated by Django 3.0.1 on 2020-11-14 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allgroups', '0011_auto_20201113_1908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlist',
            name='comment2',
        ),
    ]
