# Generated by Django 3.0.1 on 2020-11-16 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allgroups', '0013_allgroups_userlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allgroups',
            name='UserList',
        ),
    ]
