# Generated by Django 3.0.1 on 2020-11-16 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allgroups', '0015_allgroups_userlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allgroups',
            name='UserList',
            field=models.ManyToManyField(related_name='_allgroups_UserList_+', to='allgroups.Allgroups'),
        ),
    ]
