# Generated by Django 3.0.1 on 2020-11-16 21:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('allgroups', '0016_auto_20201116_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allgroups',
            name='UserList',
            field=models.ManyToManyField(related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
