# Generated by Django 3.0.1 on 2020-11-16 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allgroups', '0017_auto_20201116_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='newUserList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
