# Generated by Django 3.0.1 on 2020-11-16 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allgroups', '0018_newuserlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='newUserList',
        ),
    ]
