# Generated by Django 3.0.1 on 2020-11-16 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allgroups', '0019_delete_newuserlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allgroups',
            name='UserList',
        ),
    ]
