# Generated by Django 3.0.1 on 2020-11-17 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allgroups', '0020_remove_allgroups_userlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrueFalse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TF', models.BooleanField(default=False)),
            ],
        ),
    ]
