# Generated by Django 3.0.1 on 2020-11-17 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allgroups', '0021_truefalse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truefalse',
            name='TF',
            field=models.TextField(),
        ),
    ]
