# Generated by Django 3.0.1 on 2020-11-18 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allgroups', '0024_auto_20201118_0533'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment1',
            name='email',
            field=models.EmailField(default='null', max_length=254),
            preserve_default=False,
        ),
    ]
